### ISSUE TITLE
error: to many values to unpack

### ISSUE THREAD

**Issue by DSBxASSASSIN** [murtazahassan/Tello-Object-Tracking#1]
hi nice video i learnt a lot from it and while i was typing and lissening to you everything whent great untill i tryed to test your script its starts normal but then it gives me this error and i dont know if you can help?

Traceback (most recent call last):
  File "ObjectTrackingTello.py", line 149, in <module>
    getContours(imgDil, imgContour)
  File "ObjectTrackingTello.py", line 76, in getContours
    contours, hierarchy = cv2.findContours(img.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack (expected 2)

**Comment by murtazahassan** [comment]
hi , this could be caused due to opencv version . 
have a look at this 
https://stackoverflow.com/questions/46652754/python-opencv-valueerror-too-many-values-to-unpack?rq=1

**Comment by aliasimoglu** [comment]
> hi nice video i learnt a lot from it and while i was typing and lissening to you everything whent great untill i tryed to test your script its starts normal but then it gives me this error and i dont know if you can help?
> 
> Traceback (most recent call last):
> File "ObjectTrackingTello.py", line 149, in
> getContours(imgDil, imgContour)
> File "ObjectTrackingTello.py", line 76, in getContours
> contours, hierarchy = cv2.findContours(img.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
> ValueError: too many values to unpack (expected 2)

did you solve this issue?

**Comment by aliasimoglu** [comment]
@DSBxASSASSIN did you solve error

**Comment by DSBxASSASSIN** [comment]
ah sorry for not responding i din't see your email at first i have not
tryed it yet but i wil try it later in the evening. but thank you for even
emailing me and folowing up with me

**Comment by aliasimoglu** [comment]
thank you so much to respond

**Comment by aliasimoglu** [comment]
@DSBxASSASSIN i change the this code: contours, hierarchy = cv2.findContours(img.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
I write this code: (_, contours, hierarchy) = cv2.findContours(img.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
end I am using computer camera for this reason this code cap = cv2.VideoCapture(0) it has to practec in zero

**Comment by DSBxASSASSIN** [comment]
thank you so mutch it is working now :)
